/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScansIdRouteImport } from './routes/scans.$id'
import { Route as ScansIdVerifyRouteImport } from './routes/scans.$id.verify'
import { Route as ScansIdScopeRouteImport } from './routes/scans.$id.scope'
import { Route as ScansIdPromptsRouteImport } from './routes/scans.$id.prompts'
import { Route as ScansIdProgressRouteImport } from './routes/scans.$id.progress'
import { Route as ScansIdDashboardRouteImport } from './routes/scans.$id.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIdRoute = ScansIdRouteImport.update({
  id: '/scans/$id',
  path: '/scans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIdVerifyRoute = ScansIdVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ScansIdRoute,
} as any)
const ScansIdScopeRoute = ScansIdScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => ScansIdRoute,
} as any)
const ScansIdPromptsRoute = ScansIdPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => ScansIdRoute,
} as any)
const ScansIdProgressRoute = ScansIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ScansIdRoute,
} as any)
const ScansIdDashboardRoute = ScansIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ScansIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scans/$id': typeof ScansIdRouteWithChildren
  '/scans/$id/dashboard': typeof ScansIdDashboardRoute
  '/scans/$id/progress': typeof ScansIdProgressRoute
  '/scans/$id/prompts': typeof ScansIdPromptsRoute
  '/scans/$id/scope': typeof ScansIdScopeRoute
  '/scans/$id/verify': typeof ScansIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scans/$id': typeof ScansIdRouteWithChildren
  '/scans/$id/dashboard': typeof ScansIdDashboardRoute
  '/scans/$id/progress': typeof ScansIdProgressRoute
  '/scans/$id/prompts': typeof ScansIdPromptsRoute
  '/scans/$id/scope': typeof ScansIdScopeRoute
  '/scans/$id/verify': typeof ScansIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scans/$id': typeof ScansIdRouteWithChildren
  '/scans/$id/dashboard': typeof ScansIdDashboardRoute
  '/scans/$id/progress': typeof ScansIdProgressRoute
  '/scans/$id/prompts': typeof ScansIdPromptsRoute
  '/scans/$id/scope': typeof ScansIdScopeRoute
  '/scans/$id/verify': typeof ScansIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scans/$id'
    | '/scans/$id/dashboard'
    | '/scans/$id/progress'
    | '/scans/$id/prompts'
    | '/scans/$id/scope'
    | '/scans/$id/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scans/$id'
    | '/scans/$id/dashboard'
    | '/scans/$id/progress'
    | '/scans/$id/prompts'
    | '/scans/$id/scope'
    | '/scans/$id/verify'
  id:
    | '__root__'
    | '/'
    | '/scans/$id'
    | '/scans/$id/dashboard'
    | '/scans/$id/progress'
    | '/scans/$id/prompts'
    | '/scans/$id/scope'
    | '/scans/$id/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScansIdRoute: typeof ScansIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$id': {
      id: '/scans/$id'
      path: '/scans/$id'
      fullPath: '/scans/$id'
      preLoaderRoute: typeof ScansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$id/verify': {
      id: '/scans/$id/verify'
      path: '/verify'
      fullPath: '/scans/$id/verify'
      preLoaderRoute: typeof ScansIdVerifyRouteImport
      parentRoute: typeof ScansIdRoute
    }
    '/scans/$id/scope': {
      id: '/scans/$id/scope'
      path: '/scope'
      fullPath: '/scans/$id/scope'
      preLoaderRoute: typeof ScansIdScopeRouteImport
      parentRoute: typeof ScansIdRoute
    }
    '/scans/$id/prompts': {
      id: '/scans/$id/prompts'
      path: '/prompts'
      fullPath: '/scans/$id/prompts'
      preLoaderRoute: typeof ScansIdPromptsRouteImport
      parentRoute: typeof ScansIdRoute
    }
    '/scans/$id/progress': {
      id: '/scans/$id/progress'
      path: '/progress'
      fullPath: '/scans/$id/progress'
      preLoaderRoute: typeof ScansIdProgressRouteImport
      parentRoute: typeof ScansIdRoute
    }
    '/scans/$id/dashboard': {
      id: '/scans/$id/dashboard'
      path: '/dashboard'
      fullPath: '/scans/$id/dashboard'
      preLoaderRoute: typeof ScansIdDashboardRouteImport
      parentRoute: typeof ScansIdRoute
    }
  }
}

interface ScansIdRouteChildren {
  ScansIdDashboardRoute: typeof ScansIdDashboardRoute
  ScansIdProgressRoute: typeof ScansIdProgressRoute
  ScansIdPromptsRoute: typeof ScansIdPromptsRoute
  ScansIdScopeRoute: typeof ScansIdScopeRoute
  ScansIdVerifyRoute: typeof ScansIdVerifyRoute
}

const ScansIdRouteChildren: ScansIdRouteChildren = {
  ScansIdDashboardRoute: ScansIdDashboardRoute,
  ScansIdProgressRoute: ScansIdProgressRoute,
  ScansIdPromptsRoute: ScansIdPromptsRoute,
  ScansIdScopeRoute: ScansIdScopeRoute,
  ScansIdVerifyRoute: ScansIdVerifyRoute,
}

const ScansIdRouteWithChildren =
  ScansIdRoute._addFileChildren(ScansIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScansIdRoute: ScansIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
