"""initial schema

Revision ID: 86c959ab049c
Revises: 
Create Date: 2026-07-17 14:59:40.871576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86c959ab049c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='created', nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('monitoring_categories', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('brand_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scans_company_id_finished_at', 'scans', ['company_id', 'finished_at'], unique=False)
    op.create_index('ix_scans_status', 'scans', ['status'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw_model_out', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('ai_generated','user_edited','ai_verified')", name='ck_company_profiles_source'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'version', name='uq_company_profiles_scan_version')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('dedupe_hash', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'dedupe_hash', name='uq_prompts_scan_dedupe_hash')
    )
    op.create_index('ix_prompts_scan_id', 'prompts', ['scan_id'], unique=False)
    op.create_table('scan_entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_target', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_entities_scan_id', 'scan_entities', ['scan_id'], unique=False)
    op.create_table('scan_metrics',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('api_key_id', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'provider', name='uq_ai_responses_prompt_provider')
    )
    op.create_index('ix_ai_responses_scan_provider_status', 'ai_responses', ['scan_id', 'provider', 'status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('target_mentioned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recommended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('mentioned_companies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('evaluator_model', sa.Text(), nullable=True),
    sa.Column('evaluator_pool', sa.Text(), nullable=True),
    sa.Column('api_key_id', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('is_target', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['scan_entities.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mentions_scan_entity', 'mentions', ['scan_id', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentions_scan_entity', table_name='mentions')
    op.drop_table('mentions')
    op.drop_table('evaluations')
    op.drop_index('ix_ai_responses_scan_provider_status', table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_table('scan_metrics')
    op.drop_index('ix_scan_entities_scan_id', table_name='scan_entities')
    op.drop_table('scan_entities')
    op.drop_index('ix_prompts_scan_id', table_name='prompts')
    op.drop_table('prompts')
    op.drop_table('job_runs')
    op.drop_table('company_profiles')
    op.drop_index('ix_scans_status', table_name='scans')
    op.drop_index('ix_scans_company_id_finished_at', table_name='scans')
    op.drop_table('scans')
    op.drop_table('companies')
    # ### end Alembic commands ###
